#
# Project:	Network Information Transfer System (NITS)
# Module:	
# Programmer:	John C. Noble
# Organization:	JHU EP
# Host System:	SunOS 4
# Date Created: February 10
# Modifications:
#	$Log$
# 
# 

# Library to make (eg: libeg.a)
LIBRARY = libmcast.a 


# Source files for LIBRARY routines
SRC	= mcast_get_if.c \
	mcast_get_loop.c \
	mcast_get_ttl.c \
	mcast_join.c \
	mcast_leave.c \
	mcast_set_loop.c \
	mcast_set_ttl.c \
	sockfd_to_family.c \
	family_to_level.c

# Master include files for libraries.
include ../../../Make_templates/Make.lib
